#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MobileLifeCycleSampleApp.Droid.Resource", IsApplication=true)]

namespace MobileLifeCycleSampleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::MobileLifeCycleSampleApp.Droid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::MobileLifeCycleSampleApp.Droid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::MobileLifeCycleSampleApp.Droid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::MobileLifeCycleSampleApp.Droid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::MobileLifeCycleSampleApp.Droid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::MobileLifeCycleSampleApp.Droid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::MobileLifeCycleSampleApp.Droid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::MobileLifeCycleSampleApp.Droid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::MobileLifeCycleSampleApp.Droid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::MobileLifeCycleSampleApp.Droid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::MobileLifeCycleSampleApp.Droid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::MobileLifeCycleSampleApp.Droid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::MobileLifeCycleSampleApp.Droid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::MobileLifeCycleSampleApp.Droid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::MobileLifeCycleSampleApp.Droid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::MobileLifeCycleSampleApp.Droid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::MobileLifeCycleSampleApp.Droid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::MobileLifeCycleSampleApp.Droid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::MobileLifeCycleSampleApp.Droid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::MobileLifeCycleSampleApp.Droid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::MobileLifeCycleSampleApp.Droid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::MobileLifeCycleSampleApp.Droid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::MobileLifeCycleSampleApp.Droid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::MobileLifeCycleSampleApp.Droid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::MobileLifeCycleSampleApp.Droid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::MobileLifeCycleSampleApp.Droid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::MobileLifeCycleSampleApp.Droid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::MobileLifeCycleSampleApp.Droid.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::MobileLifeCycleSampleApp.Droid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::MobileLifeCycleSampleApp.Droid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::MobileLifeCycleSampleApp.Droid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::MobileLifeCycleSampleApp.Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::MobileLifeCycleSampleApp.Droid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::MobileLifeCycleSampleApp.Droid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::MobileLifeCycleSampleApp.Droid.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::MobileLifeCycleSampleApp.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int hockeyapp_background_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hockeyapp_background_light = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int hockeyapp_background_white = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int hockeyapp_button_background = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int hockeyapp_button_background_pressed = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hockeyapp_button_background_selected = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int hockeyapp_text_black = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int hockeyapp_text_light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int hockeyapp_text_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int hockeyapp_text_white = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hockeyapp_btn_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int button_add_response = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int button_attachment = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int button_login = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int button_refresh = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int button_send = 2131165193;
			
			// aapt resource value: 0x7f070016
			public const int button_update = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int input_email = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int input_message = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int input_name = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int input_password = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int input_subject = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int label_author = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int label_date = 2131165209;
			
			// aapt resource value: 0x7f07000b
			public const int label_last_updated = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int label_message = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int label_text = 2131165210;
			
			// aapt resource value: 0x7f070014
			public const int label_title = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int label_version = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int list_attachments = 2131165211;
			
			// aapt resource value: 0x7f07000f
			public const int list_feedback_messages = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int text_headline = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int view_header = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int web_update_details = 2131165207;
			
			// aapt resource value: 0x7f070007
			public const int wrapper_attachments = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int wrapper_feedback = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int wrapper_feedback_scroll = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int wrapper_messages = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int wrapper_messages_buttons = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int hockeyapp_activity_expiry_info = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hockeyapp_activity_feedback = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_update = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_fragment_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_view_feedback_message = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_crash_dialog_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_crash_dialog_negative_button = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_crash_dialog_neutral_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_crash_dialog_positive_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_crash_dialog_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hockeyapp_dialog_error_message = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_dialog_error_title = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_dialog_negative_button = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_dialog_positive_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_download_failed_dialog_message = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_download_failed_dialog_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_error_no_network_message = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_expiry_info_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_expiry_info_title = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_feedback_attach_file = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_feedback_attach_picture = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_feedback_attachment_button_text = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_feedback_attachment_error = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_feedback_attachment_loading = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_feedback_email_hint = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_feedback_failed_text = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_failed_title = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_generic_error = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_last_updated_text = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_message_hint = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_name_hint = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_refresh_button_text = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_response_button_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_select_file = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_select_picture = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_send_button_text = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_send_generic_error = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_send_network_error = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_sending_feedback_text = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_subject_hint = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_title = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_validate_email_empty = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_validate_email_error = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_validate_name_error = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_validate_subject_error = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_validate_text_error = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_login_email_hint = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_login_headline_text = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_login_headline_text_email_only = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_login_login_button_text = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_login_missing_credentials_toast = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_login_password_hint = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_paint_dialog_message = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_paint_dialog_negative_button = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_paint_dialog_neutral_button = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_paint_dialog_positive_button = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_paint_indicator_toast = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_paint_menu_clear = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_paint_menu_save = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_paint_menu_undo = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_permission_dialog_negative_button = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_permission_dialog_positive_button = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_permission_update_message = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_permission_update_title = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_update_button = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_update_dialog_message = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_update_dialog_negative_button = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_update_dialog_positive_button = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_update_dialog_title = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_update_mandatory_toast = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_update_version_details_label = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int library_name = 2130968647;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int HockeyApp_ButtonStyle = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int HockeyApp_EditTextStyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int HockeyApp_SingleLineInputStyle = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
